name: Check Branch Name Convention

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|docs|config|release)/[a-z0-9._-]+$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Use: feature/<name>, bugfix/<name>, etc."
            exit 1
          fi

          echo "✅ Branch name '$BRANCH_NAME' is valid."
