name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ env.HOME }}/.bun/bin:${{ env.PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Check Bun version
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
