name: TypeCheck

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run TypeScript type check
        run: npm run typecheck
